# -*- coding: utf-8 -*-
"""
Content for the WFP Sindh briefing note (single source of truth for PDF and DOCX renderers).
Block types:
  ("title", text) / ("subtitle", text) / ("meta", text)
  ("h", text)                       section heading
  ("p", text)                       paragraph; supports <b>, <i> inline tags
  ("bullets", [text, ...])          bullet list
  ("table", header_row, rows, col_fracs)
  ("footer", text)
"""

TITLE = "Sindh and Karachi: Political-Administrative Set-up, Prospective Constitutional Change and Government Counterparts"
SUBTITLE = "Briefing note for the WFP Pakistan Representative and Country Director ahead of the Sindh visit"
META = "Prepared 8 September 2026  |  Internal - for discussion  |  Sources: official notifications, Sindh Assembly record, national press; positions verified to 5 Sep 2026"

BLOCKS = [
    ("h", "1. Key messages"),
    ("bullets", [
        "<b>Predictable counterparts, constrained means.</b> The Pakistan Peoples Party (PPP) has governed Sindh without interruption since 2008 and holds 117 of 168 Assembly seats - a two-thirds majority that also gives it a constitutional veto over any redrawing of the province. Continuity of ministers and secretaries is high; fiscal space and departmental capacity, not political will, are the binding constraints on WFP's portfolio.",
        "<b>Karachi is multi-jurisdictional.</b> The city (20.4 million people; 37% of Sindh's 55.7 million) is run through overlapping provincial, municipal, federal and cantonment authorities; the elected Mayor (PPP) controls roughly a quarter of the city's land and only part of municipal functions. Urban programming needs the Commissioner/Deputy Commissioners and the KMC/Town chairs in parallel.",
        "<b>The 27th Amendment (Nov 2025) did not touch devolution.</b> It centralised judicial and defence powers at the federal level, but PPP resistance kept the 18th Amendment mandates and the NFC floor intact. Provincial ownership of WFP's sectors - nutrition, school education, food, social protection, disaster management - is intact.",
        "<b>A 28th Amendment is being discussed but is stalled.</b> Its reported agenda (local-government protection and fiscal guarantees, NFC revision, a federal coordinating role in education/health/population, new 'administrative units'/provinces) cannot pass without PPP votes. Structural change is therefore unlikely in the near term, but the debate is inflaming Centre-Sindh and PPP-MQM-P relations; expect to be asked about it and stay strictly neutral.",
        "<b>Near-term risks are fiscal and climatic, not constitutional:</b> Sindh's development freeze and surplus commitments to Islamabad, the 2026 wheat shortfall and import, and the monsoon season.",
    ]),

    ("h", "2. Political set-up"),
    ("p", "<b>Federal frame.</b> A PML-N-led coalition under Prime Minister Shehbaz Sharif depends on the PPP (President Asif Ali Zardari; Chairman Bilawal Bhutto-Zardari) for its two-thirds majority, and operates within a civil-military 'hybrid' arrangement in which the military leadership weighs heavily on strategic policy and, since July 2026, has spoken publicly on governance reform. The MQM-P, Karachi's urban party, is a junior federal partner holding the Health (Mustafa Kamal) and Education (Khalid Maqbool Siddiqui) ministries - both relevant to WFP and both used as platforms to advocate change in Karachi."),
    ("p", "<b>Sindh.</b> Chief Minister Syed Murad Ali Shah (PPP, since 2016) leads a cabinet of some 20 ministers and advisers; decisions are centralised in the CM's office (Principal Secretary Agha Wasif) and a small circle of senior ministers (Sharjeel Inam Memon, Nasir Hussain Shah, Saeed Ghani, Dr Azra Fazal Pechuho - the President's sister). Governor Nehal Hashmi (PML-N) was installed on 13 March 2026 in place of MQM-P's Kamran Tessori without consulting the MQM-P - a live grievance; the office is essentially ceremonial. The opposition is the MQM-P (37 seats; Leader of the Opposition Ali Khursheedi) with small GDA, PTI/SIC and JI blocs; Speaker Awais Qadir Shah."),
    ("p", "<b>Fault lines.</b> (i) <i>Urban-rural / PPP-MQM-P:</i> control of Karachi and Hyderabad, local-government powers (Art. 140A), the 2023 census count and the jobs quota. (ii) <i>Centre-province:</i> NFC shares, federal 'coordination' in devolved sectors and, since July 2026, the 'governance reset'/new-provinces narrative voiced by the Interior Minister and the military spokesman. Sindh's PPP has answered with an Assembly resolution rejecting any division of the province or federal territory (21 Feb 2026), calls for the Interior Minister's resignation and 'Sindh Unity' rallies scheduled for 12 September 2026. Local-government elections are due in 2027, which will sharpen the Karachi contest."),

    ("h", "3. Administrative structure"),
    ("p", "<b>Secretariat.</b> Chief Secretary Syed Asif Hyder Shah (PAS, since March 2024) heads some 40 departments and is the convening authority across them. The Planning & Development Department (Chairman Najam Ahmed Shah) is the gatekeeper for PC-1 approvals, MoUs, foreign-assisted projects and the ADP; the federal Economic Affairs Division remains the formal channel for UN and donor agreements. The Home Department (ACS Muhammad Iqbal Memon) issues the NOCs needed by NGO cooperating partners and by foreign nationals travelling to many districts, and runs the police escort regime with Sindh Police (IGP Javed Alam Odho)."),
    ("p", "<b>Field administration.</b> Six divisions under Commissioners (Karachi, Hyderabad, Sukkur, Larkana, Mirpurkhas, Shaheed Benazirabad; a seventh, Banbhore, was notified in 2014 but never operationalised) and 30 districts under Deputy Commissioners (DCs), all provincially appointed. DCs chair District Disaster Management Authorities and remain the pivot for beneficiary lists, relief distribution, land for camps and warehouses and law-and-order clearance; WFP's field-level operations run through them. Elected councils exist under the Sindh Local Government Act 2013 (amended 2021) but with narrow functions and thin funds."),
    ("p", "<b>Fiscal frame.</b> The FY2026-27 budget is Rs3.65 trillion (provincial ADP Rs385 bn plus Rs256 bn foreign-assisted), with no new taxes, a 7% pay and pension rise and a Rs110 bn development cut - Sindh's share of the Rs920 bn the provinces pledged to Islamabad under the IMF programme. Sindh draws about 24.55% of the provincial NFC pool (roughly Rs2.2 trillion); the 57.5% provincial share is unchanged pending the 11th NFC, and Islamabad is pressing provinces to co-finance BISP. <b>Food sector:</b> the Food Department missed its 2026 wheat procurement target (federal support price Rs3,500/40 kg against Sindh's preferred Rs4,000), the cabinet approved wheat imports through TCP on 5 August 2026 against a reported shortfall of about 1.7 million tonnes, and the Chief Secretary has publicly demanded reform and digitisation of the Department."),

    ("h", "4. Karachi"),
    ("p", "Karachi Division (seven districts - Karachi/South, Gulshan/East, Nazimabad/Central, Orangi/West, Korangi, Malir, Keamari; renaming partly implemented) is administered by Commissioner Syed Hassan Naqvi and seven DCs, with policing under an Additional IG (Azaad Khan). The elected tier - the Karachi Metropolitan Corporation under Mayor Barrister Murtaza Wahab (PPP, since June 2023, elected 173-161 over Jamaat-e-Islami after the MQM-P boycotted the January 2023 polls), 25 Town Municipal Corporations and 246 Union Committees - holds roads, parks, fire services and some hospitals, while water (KWSC), solid waste (SSWMB), building control (SBCA), the master plan and food-safety regulation (Sindh Food Authority) sit with provincial authorities. Six cantonment boards, DHA, the ports, railways and the airport are federal. <b>Implication:</b> any urban intervention (the Malir school-meals pilot, urban nutrition, shock-responsive safety nets) needs departmental sign-off, DC facilitation and community access through Town/UC chairs, whose party colours vary by area (PPP, JI, PTI, MQM-P). Karachi's governance is the sharpest PPP-MQM-P issue: after the Gul Plaza fire (January 2026) the MQM-P demanded that Karachi become a federal territory or 'financial capital' (Arts. 148-149); it now campaigns for court enforcement of Art. 140A and for 'administrative units' (Karachi, Larkana, Sukkur, Mirpurkhas), which the PPP reads as a prelude to dividing Sindh."),

    ("h", "5. Constitutional change: what has happened and what may come"),
    ("p", "<b>27th Amendment (enacted 13 November 2025).</b> Established a Federal Constitutional Court (FCC) that takes over constitutional and suo motu jurisdiction from the Supreme Court; created a Chief of Defence Forces under Art. 243; allowed executive-led transfer of High Court judges; raised the provincial cabinet cap from 11% to 13% of the Assembly. Clauses to remove the NFC floor (Art. 160(3A)), return education and population to the federal list and restore executive magistracy were dropped after the PPP Central Executive Committee objected (6-8 Nov 2025). <i>Effect on Sindh:</i> no change to departmental mandates or financing; disputes over LG powers or provincial boundaries will now be settled by the FCC, whose composition is executive-influenced."),
    ("p", "<b>28th Amendment (proposed, unpassed).</b> Floated since November 2025; a May 2026 tabling target lapsed, the PPP says it has not been consulted, and on 6 September 2026 the government said it would first 'seek public opinion' on new provinces. Reported contents: constitutional protection and fiscal guarantees for local governments (Art. 140A, mandatory Provincial Finance Commissions, possibly direct transfers to LGs); revision of the NFC formula (the 57.5% provincial share is under pressure); a federal coordinating role in education, health and population; enabling provisions for new provinces or 'administrative units' (proposals range from 7 to 27 units). Threshold: two-thirds of both houses plus, for any boundary change, two-thirds of the Sindh Assembly (Art. 239(4)) - the PPP holds both keys."),
    ("p", "<b>Scenario view for WFP (12-24 months).</b> <i>Status quo (most likely):</i> counterparts unchanged; the constraint is fiscal, with ADP releases likely to slip in the second half of FY27 and risk to provincially co-financed schemes (Malir pilot, Mamta CCT, Hari Card wheat support). <i>28th passes with LG/NFC clauses (plausible 2027):</i> KMC, Towns and district councils gain protected functions and funds ahead of the 2027 LG polls - new counterparts for school-feeding logistics, urban nutrition and WASH; a smaller provincial NFC share tightens Sindh's health, education and social-protection envelopes; a federal 'coordination' role brings Islamabad (MQM-P-run Health and Education ministries, BISP) back as co-decision-maker in devolved sectors, requiring dual-track engagement. <i>Administrative reorganisation short of new provinces (possible):</i> new divisions or districts (e.g., re-notification of Banbhore, splitting Karachi districts) - practical consequences only: re-mapping of DC/DDMA counterparts and field-level agreements. <i>Division of Sindh or Karachi as federal territory (remote):</i> blocked while the PPP holds two-thirds of the Sindh Assembly; it would require re-papering every provincial agreement."),

    ("h", "6. Key government stakeholders"),
    ("table",
     ["Institution / portfolio", "Incumbent(s)", "Relevance for WFP"],
     [
         ["Chief Minister of Sindh", "Syed Murad Ali Shah (PPP; since 2016); Principal Secretary Agha Wasif", "Final decision-maker; chairs cabinet, P&D and the (dormant) Provincial Disaster Management Commission. The courtesy call sets the tone for all departments."],
         ["Senior Minister - Information, Transport, Excise", "Sharjeel Inam Memon", "CM's political voice; fronts flood response and Centre-province polemics; media gatekeeper."],
         ["Health & Population Welfare", "Dr Azra Fazal Pechuho; Secretary Rehan Iqbal Baloch", "Nutrition (CMAM, Nutrition Support Programme, Lady Health Workers), Nashonuma-Mamta convergence."],
         ["School Education & Literacy", "Syed Sardar Ali Shah; Secretary Shahab Qamar Ansari", "School meals: USDA McGovern-Dole programme (USD 80 m, c. 200,000 pupils, 1,300 schools) and the Malir pilot."],
         ["Food", "Makhdoom Mehboob-uz-Zaman; Secretary (acting) Khalid Mehmood Shaikh", "Wheat procurement/import, stocks and pricing; Sindh Food Authority; Malir pilot oversight."],
         ["Labour & Social Protection", "Saeed Ghani (also PPP Karachi president); Secretary Rafiq Mustafa Shaikh", "Sindh Social Protection Authority, Mamta CCT (15 districts), shock-responsive safety nets."],
         ["Local Government & Energy", "Syed Nasir Hussain Shah; ACS Khalid Hyder Shah", "KMC/Town relations, LG law and the Art. 140A file; urban services."],
         ["Home & Law", "Zia-ul-Hassan Lanjar; ACS Muhammad Iqbal Memon; IGP Javed Alam Odho", "NOCs, security assessments, escorts; access in Kacha and border districts."],
         ["Relief / Rehabilitation / PDMA", "Minister Jabbar Khan; Adviser Gianchand Essarani; Secretary Dr Waseem Shamshad; DG PDMA Syed Salman Shah", "Monsoon/flood response, relief camps, in-kind and cash assistance with the Army; DDMAs under DCs."],
         ["Planning & Development; Finance", "Chairman P&D Najam Ahmed Shah; Secretary Planning Sajjad Hussain Abbasi; Finance Secretary Fayaz Ahmed Jatoi", "PC-1/MoU approvals, foreign-aid portfolio, Accelerated Action Plan on stunting; counterpart funding releases."],
         ["Chief Secretary; Agriculture", "Syed Asif Hyder Shah (PAS); Agriculture Secretary Suhail Ahmed Qureshi", "Apex of administration and inter-departmental convening; crop outlook, Benazir Hari Card, smallholder resilience."],
         ["Karachi: Commissioner; KMC", "Commissioner Syed Hassan Naqvi (PAS); Mayor Barrister Murtaza Wahab (PPP); Municipal Commissioner Abrar Ahmed Jaffer", "Urban facilitation, land, coordination of Karachi's DDMAs; municipal services and Town/UC access - a rising role if Art. 140A is protected."],
         ["Governor; Leader of the Opposition", "Nehal Hashmi (PML-N); Ali Khursheedi (MQM-P)", "Protocol-level federal representative without executive role; balanced outreach to the urban opposition."],
         ["Federal actors active in Sindh", "BISP Chairperson Sen. Rubina Khalid; Federal Ministers Mustafa Kamal (Health) and Khalid Maqbool Siddiqui (Education), both MQM-P; Interior Minister Mohsin Naqvi", "Nashonuma/Kafalat registry; parallel federal channels in Karachi for nutrition and education; the 'governance reset' interlocutor."],
     ],
     [0.22, 0.33, 0.45]),

    ("h", "7. Watch-points and suggested posture for the visit"),
    ("bullets", [
        "<b>Charged political week.</b> 'Sindh Unity' rallies (12 Sep) and the new-provinces debate. Avoid comment on provincial autonomy, administrative units, the census or the 28th Amendment; if pressed, cite WFP's partnership with both the Government of Sindh and federal institutions under the Country Strategic Plan 2023-2027.",
        "<b>Recognise Sindh's ownership.</b> The Malir pilot is 80% Sindh-financed and McGovern-Dole is the flagship; the CM and the Education, Food, Health and P&D leadership will expect visible credit and clarity on WFP's own resourcing.",
        "<b>Food security.</b> The 2026 wheat shortfall and TCP import, the Hari Card wheat subsidy and the Chief Secretary's push to reform the Food Department create an opening for WFP supply-chain, market-monitoring and targeting support.",
        "<b>Monsoon.</b> PDMA and the Relief/Rehabilitation departments lead with the Army; the 2025 floods saw 948 relief camps and about 109,000 people evacuated. Operational decisions sit with DCs/DDMAs rather than the provincial commission.",
        "<b>Social protection convergence.</b> BISP Nashonuma versus Sindh's Mamta CCT: federal pressure on provinces to co-fund BISP makes the agreed data-sharing and joint-targeting arrangement politically sensitive - frame it as complementarity.",
        "<b>Verify locally before meetings:</b> cabinet portfolios (last reshuffle September 2025; changes are frequent), the Food Secretary appointment, 2026 flood figures and the exact import tonnage approved.",
    ]),
]
